# base image
FROM node:latest

# set working directory
WORKDIR /usr/src/app/angular-ui

# add `/usr/src/app/angular-ui/node_modules/.bin` to $PATH
ENV PATH /usr/src/app/angular-ui/node_modules/.bin:$PATH

# install and cache app dependencies
COPY angular-ui/package.json /usr/src/app/angular-ui/package.json
RUN npm install
RUN npm install -g @angular/cli@7.3.7

# add app
COPY angular-ui/. /usr/src/app/angular-ui

# start app
CMD ng serve --host 0.0.0.0